# # This script is for installing all the packages
# install.packages("RSQLite")
# install.packages("data.table")
# install.packages("lubridate")
# install.packages("quanteda.textmodels")
# install.packages("tm")
# install.packages("lsa")
# install.packages("ggplot2")
# install.packages("knitr")
install.packages("kableExtra")
install.packages("reticulate")
